table sales_table
	lineageTag: d32effce-6989-47af-983e-4c667f4c8cac

	column Month
		dataType: string
		lineageTag: c0dadfc8-3f58-4a07-a02a-6bb1f8dddd14
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Sale Amount'
		dataType: int64
		formatString: 0
		lineageTag: fd6d3b03-59b5-4bd5-a0fa-f14daa6fbec3
		summarizeBy: sum
		sourceColumn: Sale Amount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: int64
		formatString: 0
		lineageTag: dba90569-2143-4f45-b13b-e6a2e595c1db
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition sales_table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8krMU9JRMjQwAJJGBkqxOtFKbqlJICFTkJAJRMg3sQgsDxICisfGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, #"Sale Amount" = _t, Profit = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Month", type text}, {"Sale Amount", Int64.Type}, {"Profit", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

